### If the test environment goes to sleep, any running containers will "stall"
- name: "Fix 'lxc-start' if stalled"
  delegate_to: prox
  shell: "ps x | grep -v grep | grep lxc-start | awk '{print $1}' | xargs -n 1 kill -9"
  register: lxc
  failed_when: "lxc.rc not in [0, 123]" # Ignore errors
# - debug:
#     var: lxc
- name: "Fix 'vzstart' if stalled"
  delegate_to: prox
  shell: "ps x | grep -v grep | grep vzstart | awk '{print $1}' | xargs -n 1 kill -9"
  register: vz
  failed_when: "vz.rc not in [0, 123]" # Ignore errors
# - debug:
#     var: vz

- name: "Stop containers"
  delegate_to: localhost
  proxmox:
    api_host: "{{ prox_host }}"
    api_user: "{{ prox_user }}"
    api_password: "{{ prox_password }}"

    vmid: "{{ id }}"
    state: stopped
    force: yes

- name: "Destroy containers"
  delegate_to: localhost
  proxmox:
    api_host: "{{ prox_host }}"
    api_user: "{{ prox_user }}"
    api_password: "{{ prox_password }}"

    vmid: "{{ id }}"
    state: absent

- name: "Remove orphaned SSH keys"
  delegate_to: localhost
  command: "ssh-keygen -f ~/.ssh/known_hosts -R {{ ansible_host }}"