- name: "Use root user, until SSH is configured"
  set_fact:
    ansible_user: root

- name: Gather package facts
  package_facts:
    manager: auto

  ### This is to save time, without it the install task below
  ### will check each package individually, which is slow.
  ### Yeah I know lol, it's still worth it IMO. 
- set_fact:
    missing_packages: false # Run every time
- name: "Check if packages are already installed"
  set_fact:
    missing_packages: true # Run on failure
  when: "item not in ansible_facts.packages"
  with_items: "{{ required_packages }}"
  
  ### This is looped to increase verbosity
- name: "Install packages"
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ required_packages }}"
  become: yes
  when: missing_packages == true
