---
########## Connect with IP addresses ##########
- hosts: all
  gather_facts: no
  tasks:
  - set_fact:
      ansible_host: "{{ ip }}"

- name: "Create container template"
  hosts: template
  gather_facts: no
  tasks:
  - name: "End play if template exists"
    delegate_to: prox
    shell: "pct config 200 | grep template: | awk '{printf $2}'"
    register: if_template
  - meta: end_play
    when: if_template.stdout != "1"

  - name: "Create & prepare template"
    include_role:
      name: "{{ item }}"
    with_items:
    - create
    - prepare
    - install_packages

# - name: "Create container template"
#   hosts: template
#   gather_facts: no
#   roles:
#   - create
#   - prepare
#   - install_packages
#   # - template

# - name: "Create apt cache container"

# - name: "Prepare pihole container"
#   hosts: dns_servers
#   gather_facts: no
#   roles:
#   - create
#   - prepare
#   - install_packages # This COULD be made redundant by the base container template

# - name: "Deploy pihole"
#   import_playbook: "services/pihole.yml"

# - hosts: all
#   gather_facts: no
#   tasks:
#   - set_fact:
#       ansible_host: "{{ fqdn }}"

# ########## Connect with DNS names ##########

# - name: "Prepare service containers"
#   hosts: all_services
#   gather_facts: no
#   roles:
#   - create
#   - prepare
#   # - install_packages # This COULD be made redundant by the base container template

# ### Deploy other services using DNS names
# # - import_playbook: "deploy/services/emby.yml"
# # - import_playbook: "deploy/services/wekan.yml"
# # - import_playbook: "deploy/services/pihole.yml"

# ### Confiure reverse proxy