---
### DNS workaround
- name: "Connect via IP, not DNS name"
  hosts: all
  gather_facts: no
  tasks:
  - set_fact:
      ansible_host: "{{ ip }}"

### Create/discover base template
- hosts: base
  gather_facts: no
  tasks:
  - name: "Does base template exist?"
    delegate_to: prox
    shell: "find {{ template_dir }} | grep 'vzdump.*{{ id }}.*tar'"
    register: check
    failed_when: (check.rc not in [0, 1])

  - name: "Yes! Continuing..."
    meta: end_play
    when: check.stdout != ""

  - name: "No! Creating..."
    include_role:
      name: "{{ item }}"
    with_items:
    - create
    - packages
    - backup
    when: check.stdout == ""

### Deploy pihole
  # TODO: Check if pihole container already exists
- name: "Deploy pihole"
  hosts: pihole
  gather_facts: no
  roles:
  - create
  - prepare

- import_playbook: "services/pihole.yml"

### Connect via DNS
# - hosts: all
#   gather_facts: no
#   tasks:
#   - set_fact:
#       ansible_host: "{{ fqdn }}"

# ### Deploy reverse proxy

# - name: "Prepare service containers"
#   hosts: all_services
#   gather_facts: no
#   roles:
#   - create
#   - prepare

# ### Deploy other services using DNS names
# # - import_playbook: "deploy/services/emby.yml"
# # - import_playbook: "deploy/services/wekan.yml"
# # - import_playbook: "deploy/services/pihole.yml"
