---
### Connect via IP
- hosts: all
  gather_facts: no
  tasks:
  - set_fact:
      ansible_host: "{{ ip }}"

### Create base template, if it doesn't exist
- name: "Check if base template exists"
  hosts: base
  gather_facts: no
  tasks:
  - delegate_to: prox
    shell: "find {{ template_dir }} | grep 'vzdump.*{{ id }}.*tar'" # "" == Doesn't exist
    register: check
    failed_when: (check.rc not in [0, 1])
  - debug:
      var: check

- name: "Create base check, if it doesn't exist"
  hosts: base
  gather_facts: no
  roles:

  - role: create
    when: check.stdout == ""
  - role: update_pkgs
    when: check.stdout == ""
  - role: backup
    when: check.stdout == ""
  # - block:
  #   - import_role:
  #       name: create
  #   - import_role:
  #       name: update_pkgs
  #   - import_role:
  #       name: backup
  #   when: check.stdout != ""

### Deploy pihole
- name: "Deploy pihole"
  hosts: pihole
  gather_facts: no
  roles:
  - create
  - prepare

- import_playbook: "services/pihole.yml"

### Connect via DNS
# - hosts: all
#   gather_facts: no
#   tasks:
#   - set_fact:
#       ansible_host: "{{ fqdn }}"

# - name: "Prepare service containers"
#   hosts: all_services
#   gather_facts: no
#   roles:
#   - create
#   - prepare
#   # - install_packages # This COULD be made redundant by the base container template

# ### Deploy other services using DNS names
# # - import_playbook: "deploy/services/emby.yml"
# # - import_playbook: "deploy/services/wekan.yml"
# # - import_playbook: "deploy/services/pihole.yml"

# ### Confiure reverse proxy