---
# - name: "Create container template"
#   hosts: template
#   roles:
#   - template

- name: "Deploy all containers"
  gather_facts: no
  hosts: all_cts
  vars:
    ansible_user: root # Workaround before users have sudo
  roles:
  - create
  # - restart
  - prepare
  - install_packages

  ### This drastically simplifies "deploy.yml"
  ### Doing this remove 3 roles & 5-6 plays from this file, all relating to pihole
  ### This way "deploy.yml" remains a high-level overview of tasks
  ### The only downside, is that playbooks in "playbook/" cannot use roles.
- name: "Install Pihole"
  import_playbook: "services/pihole.yml"


### Swap prox_hosts group to using DNS names
# - name: "Use DNS names instead of IPs"
#   hosts: prox_hosts
#   tasks:
#   - set_facts:
#       ansible_host: "{{}}"

### Deploy other services using DNS names
# - import_playbook: "deploy/services/emby.yml"
# - import_playbook: "deploy/services/wekan.yml"
# - import_playbook: "deploy/services/pihole.yml"

### Confiure reverse proxy