- name: "Destroy environment"
  hosts: all_cts
  gather_facts: no
  vars:
    ansible_user: root
  roles:
  - destroy

- name: "Revert Proxmox DNS server to OPNsense"
  hosts: localhost # host is overwritten inside "update_dns" task
  gather_facts: no
  vars:
    dns_server_to_apply: "{{ gateway }}"
  roles:
  - update_dns