---

##########################################################################################
### Just to keep it simple
- hosts: all
  gather_facts: no
  tasks:
  - set_fact:
      ansible_host: "{{ ip }}"

##########################################################################################
- name: "Destroy templates"
  hosts: templates
  gather_facts: no
  vars:
    ansible_user: root
  tasks:

  - name: "Show current templates"
    delegate_to: prox
    command: "find {{ template_dir }}"
    register: before
  - debug:
      var: before.stdout

  - delegate_to: prox
    shell: "rm -rf {{ template_dir }}vzdump*"
  #   register: destroy
  # - debug:
  #     var: destroy

  - name: "Show remaining templates"
    delegate_to: prox
    command: "find {{ template_dir }}"
    register: after
  - debug:
      var: after.stdout

  - name: "Remove orphaned SSH keys"
    delegate_to: localhost
    command: "ssh-keygen -f ~/.ssh/known_hosts -R {{ ansible_host }}"



