---


##########################################################################################
### Just to keep it simple
- hosts: all
  gather_facts: no
  tasks:
  - set_fact:
      ansible_host: "{{ ip }}"



##########################################################################################
- name: "Destroy environment"
  hosts: all_cts
  gather_facts: no
  vars:
    ansible_user: root
  tasks:
  - name: "Fix 'lxc-start' if stalled"
    delegate_to: prox
    shell: "ps x | grep -v grep | grep lxc-start | awk '{print $1}' | xargs -n 1 kill -9"
    register: lxc
    failed_when: "lxc.rc not in [0, 123]" # Ignore errors
  - name: "Fix 'vzstart' if stalled"
    delegate_to: prox
    shell: "ps x | grep -v grep | grep vzstart | awk '{print $1}' | xargs -n 1 kill -9"
    register: vz
    failed_when: "vz.rc not in [0, 123]" # Ignore errors

  - name: "Stop containers"
    delegate_to: localhost
    proxmox:
      api_host: "{{ prox_host }}"
      api_user: "{{ prox_user }}"
      api_password: "{{ prox_password }}"

      vmid: "{{ id }}"
      state: stopped

  - name: "Destroy containers"
    delegate_to: localhost
    proxmox:
      api_host: "{{ prox_host }}"
      api_user: "{{ prox_user }}"
      api_password: "{{ prox_password }}"

      vmid: "{{ id }}"
      state: absent

  - name: "Remove orphaned SSH keys"
    delegate_to: localhost
    command: "ssh-keygen -f ~/.ssh/known_hosts -R {{ ansible_host }}"


##########################################################################################
- name: "Revert environment DNS to OPNsense"
  hosts: prox
  gather_facts: no
  tasks:
  - name: "Edit resolv.conf"
    command: "sed -i 's/.*nameserver.*/nameserver {{ gateway }}/' /etc/resolv.conf"

  - name: "Verify DNS resolution from prox"
    shell: "nslookup example.com" # Not specifying DNS server
    register: nslookup
  - debug:
      var: nslookup.stdout



##########################################################################################
- name: "Update localhost DNS server"
  hosts: localhost
  gather_facts: no
  tasks:
  - name: "Update resolv.conf"
    shell: "sed -i 's/nameserver {{ gateway }}//' /etc/resolv.conf"
    become: yes

  - command: "cat /etc/resolv.conf"
    register: cat_resolv
  - debug:
      var: cat_resolv.stdout

  - name: "Verify DNS resolution from prox"
    shell: "nslookup example.com" # Not specifying DNS server
    register: nslookup
  - debug:
      var: nslookup.stdout





