- name: "Show new webserver URLs for {{ inventory_hostname }}"
  loop:
    - "https://{{ ip }}:{{ port }}"
    - "https://{{ fqdn }}:{{ port }}"
    # - "https://{{ ansible_host }}" ## NGINX reverse proxy
  ansible.builtin.debug:
    msg: "{{ item }}"

- name: "Verify webserver is active"
  ansible.builtin.wait_for:
    port: "{{ port }}"
    timeout: 10
