- name: "Show webserver URL (IP)"
  ansible.builtin.debug:
    msg: "https://{{ ip }}:{{ port }}"
  when: ip is defined

- name: "Show webserver URL (IP)"
  ansible.builtin.debug:
    msg: "https://{{ fqdn }}:{{ port }}"

- name: "Verify webserver is active"
  ansible.builtin.wait_for:
    port: "{{ port }}"
    timeout: 10
