- block:

  ### Prepare
  - name: "Use root user, until SSH is configured"
    set_fact:
      ansible_user: root

  - name: "Verify DNS & internet access with ping"
    command: "ping -c 2 example.com"
    register: ping
  - debug:
      var: ping.stdout

  - name: "Prepare list of packages to install"
    set_fact:
      packages_to_check: "{{ required_packages }}"

  - name: "Get apt updates"
    apt:
      update_cache: yes


  ### Update (Base template only)
  - block:
    - name: "Install updates"
      apt:
        upgrade: full
      register: update

    - name: "Append base packages to install list"
      set_fact:
        packages_to_check: "{{ base_packages + required_packages }}"

    # when: inventory_hostname == "base"
    when: base_packages is defined # Same thing

  ### Install packages
  - name: "Gather package facts"
    package_facts:
      manager: auto
  - set_fact:
      missing_packages: false # Run every time

  ### TODO: Check, then add to "packages_to_install"
  - name: "Create empty list"
    set_fact:
      packages_to_install: []

  - name: "Populate list of packages to be installed" # Looped to increase verbosity
    set_fact:
      missing_packages: true
      packages_to_install: "{{ packages_to_install + [item] }}"
    when: "item not in ansible_facts.packages"
    # when: "pkg_to_check not in ansible_facts.packages"
    # loop_control: # Avoid warnings from reusing "{{ item }}"
    #   loop_var: pkg_to_check
    with_items: "{{ packages_to_check }}"
    
  - name: "Install packages"
    apt:
      # pkg: "{{ pkg_to_install }}"
      pkg: "{{ item }}"
    with_items: "{{ packages_to_install }}"
    # loop_control: # Avoid warnings from reusing "{{ item }}"
    #   loop_var: pkg_to_install
    become: yes
    when: missing_packages == true
    retries: 3

### Fail condition
  when: (inventory_hostname == "base") or (required_packages is defined)
