
### Prepare
- name: "Use root, for simplicity"
  set_fact:
    ansible_user: root

- name: "Disable UFW in preperation"
  ufw:
    state: disabled

### Configure
- name: "Deny all"
  # command: "ufw default deny incoming"
  ufw:
    policy: deny

- name: "Allow SSH + primary port"
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: any
  loop: "{{ [22] + [port] }}"

- name: "Allow any additional ports"
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: any
  loop: "{{ additional_ports }}"
  when: additional_ports is defined

### Enable
- name: "Enable UFW"
  ufw:
    state: enabled

# - name: "Enable logging"
#   ufw:
#     logging: on

### Verify
- name: "Show firewall status"
  command: "ufw status verbose"
  register: status
- debug:
    var: status.stdout
