### TODO: Research
# https://docs.ansible.com/ansible/latest/collections/community/general/
# https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html
# https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_template_module.html
# https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_snap_module.html#ansible-collections-community-general-proxmox-snap-module

### Steps:
# pct stop 200
# pct template 200
# pct config 200 | grep template: | awk '{printf $2}' --> "1" if template



- name: "Check if template exists"
  delegate_to: prox
  shell: "pct config 200 | grep template: | awk '{printf $2}'"
  register: if_template

- name: "End playbook if template exists"
  meta: end_play
  when: if_template.stdout != "1"

### Else, continue

- name: "Create base container"
  delegate_to: prox
  command: "pct template {{ id }}"


# - name: "Prepare base container"

# - name: "Update"

# - name: "Rank apt mirrors"

# - name: "Upgrade"


# - name: "Install essential packages"

# - name: "???"

# - name: "Convert base container to template"

# - name: "Verify template exists"