### TODO: Add -v (--verbose) flag?

---
### Workaround???
  ### TODO: FIX
- name: "Literally do nothing, but everything breaks if you don't?"
  hosts: all_but_localhost
  gather_facts: no
  tasks:
  # - debug:
  #     var: ansible_host
  - set_fact:
      ansible_host: "{{ ip }}"
  # - debug:
  #     var: ansible_host

### Base
- name: "Discover/Create base template"
  hosts: base
  gather_facts: no
  tasks:
  - name: "Check if base template exists"
    delegate_to: prox
    shell: "find {{ template_dir }} | grep 'vzdump.*{{ id }}.*tar' | cat"
    register: check

  - name: "Creating base template"
    include_role:
      name: "{{ item }}" # Gross, very gross
    loop:
    - create
    - packages
    - backup # This deletes the container!
    when: check.stdout == ""  # Else, continue

# ## Deploy infrastructure
# - name: "Deploy infrastructure containers"
#   hosts: infrastructure
#   gather_facts: no
#   roles:
#   - create
#   - prepare
#   - packages
#   - firewall

# ### Configure infrastructure
# - import_playbook: "services/pihole.yml" ### TODO: Check & skip SMARTER if already installed
# # - import_playbook: "services/proxy.yml"
# # - import_playbook: "services/ca.yml"

### Deploy services
- name: "Prepare service containers"
  hosts: all_services
  gather_facts: no
  roles:
  - create
  - prepare
  - packages
  - firewall
  # - add_dns_records
  # - "deploy_{{ inventory_hostname }}" # Instead of import_playbook?

### Configure services
# - import_playbook: "services/apache.yml"
# - import_playbook: "services/emby.yml"
# - import_playbook: "services/wekan.yml"
- import_playbook: "services/scraper.yml"
