- name: Create new SSH key for {{ inventory_hostname }}
  delegate_to: localhost
  community.crypto.openssh_keypair:
    path: "{{ ansible_ssh_private_key_file }}"
    type: rsa
    size: 4096
    state: present
    force: false
