# ansible-playbook -i inv.yml simple/start_CT.yml

---
- name: "Proxmox: Start CT"
  hosts: prox
  gather_facts: no
  tasks:
  - name:
    command: "pct start {{ hostvars[item].id }}"
    become: yes
    with_items: "{{ groups['prox_hosts_all_ips'] }}"

- name: "Wait for containers to be reachable"
  hosts: prox_hosts_all_ips # TODO: DNS
  gather_facts: no
  vars:
    ansible_user: root
    # Only required before passwordless sudo is configured
  tasks:
  - wait_for_connection:
      timeout: 10
    retries: 3
    delay: 3
    register: wait_result
    until: wait_result.failed == False
  # - debug:
  #     var: wait_result

