### SSH workaround
- name: "Use root user, until SSH is configured"
  set_fact:
    ansible_user: root

### User
- name: "Create new user"
  user:
    name: "{{ user }}"
    password: "{{ password | password_hash('sha512') }}"
    shell: /usr/bin/bash
    append: yes
    groups: sudo

### Sudo
- name: "Grant passwordless sudo"
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

### SSH
- name: "Create ~/.ssh"
  file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0700"

- name: "Authorise localhost SSH key"
  copy:
    src: ~/.ssh/id_rsa.pub # localhost
    dest: "/home/{{ user }}/.ssh/authorized_keys" # remote host
    # content: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"

### Verify
- name: "Verify DNS & internet access with ping"
  command: "ping -c 3 example.com"
  register: ping
- debug:
    var: ping.stdout

### Revert SSH workaround
- set_fact:
    ansible_user: "{{ inventory_hostname }}"