- name: Check if container is already running
  delegate_to: prox
  vars: ### NOTE: Workaround for when the container isn't responding
    ansible_ssh_private_key_file: "{{ hostvars['prox'].ansible_ssh_private_key_file }}"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      pct status {{ id }} | grep running
  register: check_if_ct_running
  changed_when: check_if_ct_running.rc != 0
  failed_when: false ### Ignore failures, we just want the stdout

- name: Create CT and install packages
  when: check_if_ct_running.stdout == ""
  block:

    # ### Just making sure, in case CT exists but isn't running
    # - name: Include task file 'destroy.yml'
    #   ansible.builtin.include_tasks: destroy.yml

    - name: Include role 'prox-lxc' with tasks from 'create'
      ansible.builtin.include_role:
        name: prox-lxc
        tasks_from: create

    - name: Include role 'install-packages'
      ansible.builtin.include_role:
        name: install-packages
