---

all:
  vars:
    ### Network settings
    # subnet: "YOUR_SUBNET_HERE"
    subnet: "10.1.1"
    ip: "{{ subnet }}.{{ id }}"
    # mask: "255.255.255.0"
    gateway: "{{ subnet }}.1"

    ### DNS settings
    domain: test.lan
    fqdn: "{{ inventory_hostname }}.{{ domain }}"
    dns: "{{ hostvars['pihole'].ip }}"

    ### Ansible vars
    ansible_ssh_host: "{{ ip }}"
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/prox_automation_{{ inventory_hostname }}
    ansible_ssh_public_key_file: "{{ ansible_ssh_private_key_file }}.pub"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

    ### Proxmox vars
    prox_ct_template_dir: /var/lib/vz/template/cache
    prox_iso_dir: /var/lib/vz/template/iso

    ### Misc. vars
    repo_dir: "{{ inventory_dir | dirname | dirname }}"
    password_file: "{{ repo_dir }}/password.txt"

  hosts:
    prox:
      # id: "YOUR_HOST_IP_AFFIX_HERE"
      id: 240
      port: 8006

  children:
    cts:
      hosts:
        base-ct:
          id: 241
          # base_template: ubuntu-20.04-standard_20.04-1_amd64.tar.gz
          # base_template: ubuntu-21.10-standard_21.10-1_amd64.tar.zst
          # base_template: ubuntu-22.04-standard_22.04-1_amd64.tar.zst
          base_template: ubuntu-22.10-standard_22.10-1_amd64.tar.zst
          # base_template: alpine-3.15-default_20211202_amd64.tar.xz
          base_packages: [git, curl, unzip, idn2, htop, tree]

        pihole:
          id: 242
          port: 80
          cname: "{{ domain }}"

    vms:
      hosts:
        base-vm:
          id: 9000
          ### 22.04 LTS
          cloud_init_img_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
          cloud_init_img: "ubuntu-{{ cloud_init_img_url | basename }}"
          base_packages: [git, curl, unzip, idn2, htop, tree]

        portainer:
          id: 252
          port: 9443

    # docker_containers:
    #   hosts:
    #     scraper:
    #       id: 125
    #       # port: 80
    #       port: 5000
    #       ct_cores: 2
    #       ct_memory: 1024
    #       ct_swap: 100
    #       # required_packages: [apache2,php,libapache2-mod-php,python3-pip,firefox,firefox-geckodriver]
    #       # required_packages: [apache2,php,libapache2-mod-php,python3-pip,firefox]
    #       required_packages: [python3-pip,firefox,firefox-geckodriver]
    #       # additional_ports: [3306, 33060]
    #       # ct_features:
    #       # - fuse=1
    #       # - mount=nfs
    #       # - nesting=1
    #       # ct_custom_configs:
    #       # - "lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file 0 0"
