---

all:
  vars:
    env: dev
    ### Network settings
    subnet: "10.1.1" ### <-------------------------- YOUR SUBNET HERE
    ip: "{{ subnet }}.{{ id }}"
    gateway: "{{ subnet }}.1"

    ### DNS settings
    domain: test.lan ### <-------------------------- YOUR DOMAIN HERE
    fqdn: "{{ inventory_hostname }}.{{ domain }}"
    dns: "{{ hostvars['pihole'].ip }}"
    backup_dns: "1.1.1.1"

    ### Ansible vars
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/prox_automation_{{ env }}_{{ inventory_hostname }}
    ansible_ssh_public_key_file: "{{ ansible_ssh_private_key_file }}.pub"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

    ### Proxmox vars
    prox_ct_template_dir: /var/lib/vz/template/cache
    # prox_iso_dir: /var/lib/vz/template/iso ### Not using VMs at the moment

    ### Misc. vars
    prox_repo_dir: "{{ inventory_dir | dirname | dirname }}"
    prox_password_file: "{{ prox_repo_dir }}/prox_password_{{ env }}.txt"
    # portainer_password_file: "{{ prox_repo_dir }}/portainer_password.txt"
    http_protocol: http
    disable_squid_deb_proxy: false
    homelab_git_url: https://github.com/jason-galea
    # requires_nested_docker: false
    apt_packages: false
    pip_packages: false

  hosts:
    prox:
      id: 240 ### <-------------------------- YOUR PROXMOX IP HERE
      port: 8006
      http_protocol: https

  children:

    cts:
      vars:
        ct_template: ubuntu-22.10-standard_22.10-1_amd64.tar.zst
        # apt_packages: [ca-certificates, curl, gnupg, docker.io, python3-pip] ### ~90MB, thank you squid ;D
        # pip_packages: [docker, docker-compose] ### For "community.docker.docker_compose"
        # # pip_packages: [requests==2.28.1, httpie] ### https://github.com/docker/docker-py/issues/3113

      children:

        infra:
          hosts:
            squid:
              id: 241
              ct_disk: 16
              apt_packages: [squid-deb-proxy]
              port: 8000
              disable_squid_deb_proxy: true
            pihole:
              id: 242
              ct_features:
                - nesting=1
              apt_packages: [python3-pip, git, docker.io]
              pip_packages: [docker, docker-compose]
              port: 8053
              infra_repo_name: homelab_pihole

        services:
          hosts:
            nginx:
              id: 245
              ct_features:
                - nesting=1
              apt_packages: [python3-pip, git, docker.io]
              pip_packages: [docker, docker-compose]
              port: 80
              infra_repo_name: homelab_nginx
