---

all:
  vars:
    ### Network settings
    # subnet: "YOUR_SUBNET_HERE"
    subnet: "10.1.1"
    ip: "{{ subnet }}.{{ id }}"
    # mask: "255.255.255.0"
    gateway: "{{ subnet }}.1"

    ### DNS settings
    domain: test.lan
    fqdn: "{{ inventory_hostname }}.{{ domain }}"
    dns: "{{ hostvars['pihole'].ip }}"
    backup_dns: 10.1.1.111
    # backup_dns: 1.1.1.1
    backup_domain: galea.lan

    ### Ansible vars
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/prox_automation_{{ inventory_hostname }}
    ansible_ssh_public_key_file: "{{ ansible_ssh_private_key_file }}.pub"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

    ### Proxmox vars
    prox_ct_template_dir: /var/lib/vz/template/cache
    # prox_iso_dir: /var/lib/vz/template/iso ### Not using VMs at the moment

    ### Misc. vars
    repo_dir: "{{ inventory_dir | dirname | dirname }}"
    prox_password_file: "{{ repo_dir }}/prox_password.txt"
    portainer_password_file: "{{ repo_dir }}/portainer_password.txt"
    http_protocol: http
    disable_squid_deb_proxy: false

  hosts:
    prox:
      # id: "YOUR_HOST_IP_AFFIX_HERE"
      id: 240
      port: 8006
      http_protocol: https

  children:

    cts:
      vars:
        ct_template: ubuntu-22.10-standard_22.10-1_amd64.tar.zst
      hosts:
        squid:
          id: 241
          apt_packages: [squid-deb-proxy]
          port: 8000
          disable_squid_deb_proxy: true
        pihole:
          id: 242
          apt_packages: [git]
          port: 80
          cname: "{{ domain }}"
        gitlab:
          id: 243
          ct_template: ubuntu-22.04-standard_22.04-1_amd64.tar.zst
          ct_cores: 4
          ct_memory: 4096
          ct_swap: 512
          ct_disk: 16
          disable_squid_deb_proxy: true
          apt_packages: [curl, openssh-server, ca-certificates, tzdata, perl]
          port: 80
        portainer:
          id: 244
          ct_cores: 4
          ct_memory: 4096
          ct_swap: 512
          ct_disk: 16
          apt_packages: [docker.io, python3-pip, jq]
          pip_packages: [requests==2.28.1, httpie] ### https://github.com/docker/docker-py/issues/3113
          # ct_features:
          #   - nesting=1
          ct_unprivileged: false
          # port: 8000 ### Remote agent polling https://github.com/portainer/portainer-docs/issues/91
          port: 9000 ### HTTP
          # port: 9443 ### HTTPS

    docker_containers:
      hosts:
        nginx:
          repo: https://github.com/jason-galea/price_scraper.git
          port: 80

        scraper:
          repo: https://github.com/jason-galea/price_scraper.git
          port: 5000
