- name: Stop VM
  vars: ### NOTE: Workaround, only required when container isn't online
    ansible_ssh_private_key_file: "{{ hostvars['prox'].ansible_ssh_private_key_file }}"
  delegate_to: prox
  ansible.builtin.command: "qm stop {{ id }}"
  register: convert_base_vm_to_template
  changed_when: convert_base_vm_to_template.rc != 0
  failed_when: convert_base_vm_to_template.rc not in [0, 255]


- name: Convert base VM to template
  vars: ### NOTE: Workaround, only required when container isn't online
    ansible_ssh_private_key_file: "{{ hostvars['prox'].ansible_ssh_private_key_file }}"
  delegate_to: prox
  ansible.builtin.command: "qm template {{ id }}"
  register: convert_base_vm_to_template
  changed_when: convert_base_vm_to_template.rc != 0
  failed_when: convert_base_vm_to_template.rc not in [0, 255]
