# TODO:
# Currently the test environment (Proxmox & OPNsense on Hyper-V) is manually configured
# This file would automate the deploy of that test environment

### This playbook expects a freshly install OPNsense VM, with IP matching inv.yml
### For example:
# Create VM in Hyper-V
# Boot ISO, (LIST LIVE INSTALL OPTIONS HERE)
# VM will be ready after first reboot


---
- name: "Localhost: Prepare OPNsense for SSH"
  hosts: localhost
  gather_facts: no
  vars:
    password: "{{ lookup('file', '../password.txt') }}" # Might be useful for ssh-copy-id?
  tasks:
    ### (Remove previous SSH host)
    # ssh-keygen -f "/home/jg/.ssh/known_hosts" -R "172.26.0.2"
    # BUILTIN????
  - name:

    ### Add SSH key for root
    # ssh-copy-id -o "StrictHostKeyChecking no" root@172.26.0.2
    # BUILTIN????
  - name:
    

- name: "Localhost: Prepare prox for SSH"
  hosts: prox
  gather_facts: no
  vars:
    ansible_user: root
  tasks:
  ### ???
  - name


### Add SSH key for "prox"
# ssh-copy-id -o "StrictHostKeyChecking no" prox@172.26.0.2

### (Verify)
# ssh prox@172.26.0.2
# Access website: https://172.26.0.2:8006/
# Deploy CTs: ./deploy.sh