- name: Create new SSH key for {{ inventory_hostname }}
  delegate_to: localhost
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: rsa
    size: 4096
    state: present
    force: false
