### Stop
- name: "Stop container"
  delegate_to: localhost
  community.general.proxmox:
    api_host: "{{ hostvars['prox'].ansible_ssh_host }}"
    api_user: root@pam
    api_password: "{{ hostvars['prox'].password }}"

    vmid: "{{ id }}"
    state: stopped

- name: "Remove network config"
  delegate_to: prox
  ansible.builtin.command: "pct set {{ id }} --delete net0"
  register: remove_network_config
  changed_when: remove_network_config.rc != 0

- name: "Backup container with vzdump"
  delegate_to: prox
  ansible.builtin.command: "vzdump {{ id }} --mode stop --dumpdir {{ template_dir }} --compress zstd"
  register: vzdump_container
  changed_when: vzdump_container.rc != 0

- name: "DEBUG: Show output of container backup"
  ansible.builtin.debug:
    var: convert.stdout

- name: "Wait for container to finish being deleted"
  ansible.builtin.pause:
    seconds: 2
