- name: "Destroy VMs"
  delegate_to: localhost
  community.general.proxmox_kvm:
    node: prox
    api_host: "{{ hostvars['prox'].ansible_ssh_host }}"
    api_user: root@pam
    api_password: "{{ lookup('file', password_file) }}"

    vmid: "{{ id }}"
    state: absent
    force: true

# - name: "Wait for VMs to finish being destroyed"
#   ansible.builtin.pause:
#     seconds: 2

- name: "Include role 'ssh' with tasks from 'remove'"
  ansible.builtin.include_role:
    name: ssh
    tasks_from: remove
