- name: Check if VM is already running
  vars: ### NOTE: Workaround, only required when container isn't online
    ansible_ssh_private_key_file: "{{ hostvars['prox'].ansible_ssh_private_key_file }}"
  delegate_to: prox
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      qm list | grep -E '{{ id }}\ *running'
    executable: /bin/bash
  register: check_if_vm_running
  changed_when: check_if_vm_running.rc != 0
  failed_when: false ### Ignore failures, we just want the stdout

- name: Create VM and install packages
  when: check_if_vm_running.stdout == ""
  block:

    - name: Include task file 'create.yml'
      ansible.builtin.include_role:
        name: prox_kvm
        tasks_from: create


    - name: Include role 'install_packages'
      ansible.builtin.include_role:
        name: install_packages
