### TODO: USE THIS:
# https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html#examples
### NOTE: APPARMOR IS BROKEN!!!1!
### TO FIX: If "nested" (ie. running docker/podman containers), disable apparmor

# Guides:
# https://www.techrepublic.com/article/how-to-install-the-wekan-kanban-server/
# https://blog.eldernode.com/install-wekan-kanban-server-on-ubuntu-20-04/

# Fixing snaps in CTs:
# https://forum.proxmox.com/threads/ubuntu-snaps-inside-lxc-container-on-proxmox.36463/

### Wekan commands:
# DONE # sudo apt install -y snapd nginx squashfuse
# DONE # sudo systemctl enable --now nginx
# DONE # sudo systemctl enable --now snapd
# sudo snap install wekan
# sudo snap set wekan siteurl='http://{{ ansible_host }}'
# sudo snap set wekan port='{{ port }}'
# DONE # sudo systemctl restart snap.wekan.mongodb
# DONE # sudo systemctl restart snap.wekan.wekan
# (sudo systemctl status snap.wekan.wekan) # Should be "active (running)"

---
- name: "Install Wekan"
  hosts: wekan
  gather_facts: no
  become: yes
  tasks:

  ### Install
  - name: "Snap install Wekan"
    snap:
      name: wekan
    register: snap_install
    retries: 3
    until: snap_install.rc == 0
  - debug:
      var: snap_install
    when: snap_install.stdout is defined

  ### Configure
  - name: "Snap set Wekan URL"
    command: "snap set wekan siteurl='http://{{ ansible_host }}'"
    register: snap_url
  # - debug:
  #     var: snap_url.stdout

  - name: "Snap set Wekan port"
    command: "snap set wekan port='{{ port }}'"
    register: snap_port
  # - debug:
  #     var: snap_port.stdout

  - name: "Restart MongoDB and Wekan"
    systemd:
      name: "{{ item }}"
      state: restarted
    loop:
    - snap.wekan.mongodb
    - snap.wekan.wekan

  ### Verify
  - name: "Verify webserver at http://{{ ansible_host }}:{{ port }} "
    wait_for:
      port: "{{ port }}"
    delay: 3
