# ansible-playbook -i inventory.ini services/apache.yml

---
- name: "Deploy Apache"
  hosts: apache
  gather_facts: no
  # vars:
  #   webserver: "http://{{ ansible_hostname }}" 
  tasks:
    # CBF allowing custom ports lol, would have to edit the config file
  - name: "Install apache package"
    apt:
      pkg: apache2
      update_cache: yes
      state: present
    become: yes
    register: install
  - debug:
      var: install.stdout
    when: install.stdout is defined

  - name: "Verify webserver at http://{{ ansible_host }}:{{ port }}"
    wait_for:
      port: "{{ port }}"
      delay: 3

  # TODO: Configure reverse proxy
  # Maybe like this:
  # 1. Apache is deployed & configured before any other services
  # 2. As other services are deployed, they create new proxy sites in apache
  # 3. New services could be accessed from "http://XYZ.test.lan", where *.test.lan is routed to apache by DNS
  # 4. Finally, OPNsense could port forward apache, to have all services available from "WAN"
  # - name: "Configure"
  #   command: ???