---
- name: "Deploy Apache"
  hosts: apache
  gather_facts: no
  tasks:
    ### TODO: MOVE THIS LOGIC INTO "required_packages" + "packages" role
  - name: "Install apache package"
    apt:
      pkg: apache2
      update_cache: yes
      state: present
    become: yes
    register: install
  - debug:
      var: install.stdout
    when: install.stdout is defined

  - name: "Verify webserver at http://{{ ansible_host }}:{{ port }}"
    wait_for:
      port: "{{ port }}"
      delay: 3
