---
- name: "Deploy Price Scraper"
  hosts: scraper
  gather_facts: no
  # become: yes # User is "root" already
  tasks:

  - name: "Upgrade pip"
    pip: 
      name: pip
      extra_args: --upgrade
  
  - name: "Install python modules"
    pip:
      name: "{{ item }}"
    with_items:
    - selenium
    - mysql-connector-python
    - beautifulsoup4

  - name: "Delete old /var/www"
    file:
      path: /var/www
      state: absent

  - name: "Clone price_scraper repo to /var/www"
    git:
      repo: "https://github.com/jason-galea/price_scraper"
      version: "removing_sql" # branch
      dest: "/var/www"

    ### Apache default permissions:
    # /var/www/html/ --> 755 root:root 
    # /var/www/html/index.html --> 644 root:root
  - name: "Change permissions"
    file:
      path: /var/www
      state: directory
      mode: "0755"
      recurse: yes

  - name: "Restart Apache service"
    service:
      name: apache2
      state: restarted
  - shell: "systemctl status apache2"
    register: apache2_status
  - debug:
      var: apache2_status.stdout

  - name: "Verify with test job"
    shell: "/var/www/script/scrape.py"
    register: scrape
  - debug:
      var: scrape.stdout











