# ansible-playbook -i inv.yml services/pihole.yml

# Expects host "pihole" to be deployed according to inv.yml

---
- name: "Deploy Pihole (via docker)"
  hosts: pihole
  gather_facts: no
  vars:
    setupvars: "/etc/pihole/setupVars.conf"
  tasks:

  ### Install docker
  ### https://docs.docker.com/engine/install/ubuntu/
  # sudo apt-get update -y
  # sudo apt-get install -y ca-certificates curl gnupg lsb-release git
  # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  # echo \
    # "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    # $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  # sudo apt-get update -y
  # sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose

  ### Steps to set up pihole in docker
  ### https://hub.docker.com/r/pihole/pihole
  ### https://github.com/pi-hole/docker-pi-hole
  # git clone https://github.com/pi-hole/docker-pi-hole.git
  # cd docker-pi-hole/
  # cp docker-compose.yml.example docker-compose.yml
  # sed -i "s/.*TZ:.*/      TZ: 'Australia\/Melbourne'/" docker-compose.yml
  # sed -i "s/.*WEBPASSWORD:.*/      WEBPASSWORD: 'abc##123'/" docker-compose.yml
  ### Apply ubuntu fixes
  # sudo sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf
  # sudo sh -c 'rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'
  # sudo systemctl restart systemd-resolved

  ### Build and run image
  # sudo docker-compose up -d


  # - name: "Verify webserver"
  #   uri:
  #     # url: "http://{{ ansible_host }}:{{ port }}" #
  #     url: "http://{{ ansible_host }}/admin"
  #     delay: 3

  # - name: "Change Proxmox DNS server to pihole"