- name: "Start containers"
  delegate_to: localhost
  proxmox:
    api_host: "{{ prox_host }}"
    api_user: "{{ prox_user }}"
    api_password: "{{ prox_password }}"

    vmid: "{{ id }}"
    state: restarted
    force: yes

- name: "Verify containers are online"
  wait_for_connection:
    timeout: 10