### A records
- name: Create/wipe A records file
  ansible.builtin.copy:
    content: ""
    dest: "{{ a_records_file }}"
    force: true
    owner: root
    group: root
    mode: "644"

- name: Create A records ### E.G: "1.2.3.4 a.test.lan"
  loop: "{{ groups['cts'] + ['prox'] }}"
  ansible.builtin.lineinfile:
    dest: "{{ a_records_file }}"
    line: "{{ hostvars[item].ip }} {{ hostvars[item].fqdn }}"


### CNAME records
- name: Create/wipe CNAME records file
  ansible.builtin.copy:
    content: ""
    dest: "{{ cname_records_file }}"
    force: true
    owner: root
    group: root
    mode: "644"

- name: Create CNAME records ### E.G: "cname=cname.test.lan,a.test.lan"
  loop: "{{ groups['cts'] + ['prox'] }}"
  ansible.builtin.lineinfile:
    dest: "{{ cname_records_file }}"
    line: "cname={{ hostvars[item].cname }},{{ hostvars[item].fqdn }}"
  when: hostvars[item].cname is defined

- name: Create CNAME records for docker containers, running on Portainer ### E.G: "cname=cname.test.lan,a.test.lan"
  loop: "{{ groups['docker_containers'] }}"
  ansible.builtin.lineinfile:
    dest: "{{ cname_records_file }}"
    line: "cname={{ hostvars[item].fqdn }},{{ hostvars['portainer'].fqdn }}"


### Restart
- name: Restart DNS
  ansible.builtin.command: "pihole restartdns"
  register: pihole_restartdns
  changed_when: pihole_restartdns.rc != 0
