### Example playbook with required vars:
# - name: Revert DNS server to original settings
#   hosts: localhost, prox
#   gather_facts: false
#   vars_prompt:
#     - name: ansible_become_password
#       prompt: Please enter your localhost sudo password
#   vars:
#     resolv: /etc/resolv.conf
#   tasks:

#     ### NOTE: Vars 'domain' and 'dns' are set in the inventory
#     - name: Set /etc/resolv.conf to use new domain & IP
#       ansible.builtin.include_role:
#         name: pihole
#         tasks_from: update_resolv_conf

#     - name: Revert /etc/resolv.conf to backup domain & IP
#       vars:
#         domain: "{{ backup_domain }}"
#         dns: "{{ backup_dns }}"
#       ansible.builtin.include_role:
#         name: pihole
#         tasks_from: update_resolv_conf


- name: Add backup domain & dns server to {{ resolv }}
  become: true
  ansible.builtin.template:
    src: templates/resolv.conf.j2
    dest: "{{ resolv }}"
    mode: "644"

- name: Get contents of {{ resolv }}
  ansible.builtin.command: cat {{ resolv }}
  register: cat_resolv
  changed_when: cat_resolv.rc != 0

- name: Show contents of {{ resolv }}
  ansible.builtin.debug:
    var: cat_resolv.stdout_lines
