- name: "Check if pihole is already installed"
  ansible.builtin.stat:
    path: /usr/local/bin/pihole
  register: stat_pihole_bin

- name: "Check if pihole webserver is active"
  ansible.builtin.wait_for:
    port: "{{ port }}"
    timeout: 3
  register: wait_for_pihole_webserver
  failed_when: false ### Ignore fails, we just want the return code

# - name: "DEBUG: wait_for_pihole_webserver"
#   ansible.builtin.debug:
#     var: wait_for_pihole_webserver

- name: Include tasks to install & populate DNS records
  when: not ( (stat_pihole_bin.stat.exists) and (wait_for_pihole_webserver.state == 'started') )
  block:

    - name: Include task file 'install.yml'
      ansible.builtin.include_tasks: install.yml

    - name: Include task file 'populate_records.yml'
      ansible.builtin.include_tasks: populate_records.yml
