- name: "DEBUG: Get contents of {{ prox_ct_template_dir }}"
  delegate_to: prox
  ansible.builtin.command: "ls -lh {{ prox_ct_template_dir }}"
  register: ls_prox_ct_template_dir
  changed_when: ls_prox_ct_template_dir.rc != 0

- name: "DEBUG: Show contents of {{ prox_ct_template_dir }}"
  ansible.builtin.debug:
    var: ls_prox_ct_template_dir.stdout_lines
