- name: "Use root user, until SSH is configured"
  set_fact:
    ansible_user: root

- name: "Create containers"
  delegate_to: localhost
  proxmox:
    api_host: "{{ prox_host }}"
    api_user: "{{ prox_user }}"
    api_password: "{{ prox_password }}"

    vmid: "{{ id }}"

    node: "{{ ct_node }}"
    state: "{{ ct_state }}" 
    netif: "{{ ct_netif }}"
    ostemplate: "{{ ct_ostemplate }}"
    hostname: "{{ ct_hostname }}"
    password: "{{ ct_password }}"
    pubkey: "{{ ct_pubkey }}"
    cores: "{{ ct_cores }}"
    memory: "{{ ct_memory }}"
    swap: "{{ ct_swap }}"
    disk: "{{ ct_disk }}"
    storage: "{{ ct_storage }}"
    unprivileged: "{{ ct_unprivileged }}"
    onboot: "{{ ct_onboot }}"
    features: "{{ ct_features }}"
    
- name: "Start containers"
  delegate_to: localhost
  proxmox:
    api_host: "{{ prox_host }}"
    api_user: "{{ prox_user }}"
    api_password: "{{ prox_password }}"

    vmid: "{{ id }}"
    state: started

- name: "Verify containers are online"
  wait_for_connection:
    timeout: 30

- set_fact:
    ansible_user: "{{ inventory_hostname }}"