- name: "Check if container already exists"
  delegate_to: prox
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      pct list | grep -E '{{ id }}\ *running'
    executable: /bin/bash
  register: check_if_ct_exists
  changed_when: check_if_ct_exists.rc != 0
  failed_when: false ### Ignore failures, we just want the stdout

- name: "Creating container"
  loop:
    - create
    - install_packages
  ansible.builtin.include_role:
    name: create_ct
    tasks_from: "{{ item }}"
  when: check_if_ct_exists.stdout == ""
