- name: "Verify DNS & internet access with ping"
  ansible.builtin.command: "ping -c 2 example.com"
  register: verify_dns_internet
  changed_when: verify_dns_internet != 0

- name: "Install base packages and upgrade apt"
  when: "'base' in inventory_hostname"
  block:

    - name: "Install base packages"
      ansible.builtin.apt:
        pkg: "{{ base_packages }}"
        update_cache: true

    - name: "Upgrade apt packages"
      ansible.builtin.apt:
        upgrade: true

    # - name: "Install apk updates"
    #   community.general.apk:
    #     upgrade: true
    #   register: update
    #   when: distro == "alpine"


### Install packages
- name: "Install apt packages"
  ansible.builtin.apt:
    pkg: "{{ required_packages }}"
    update_cache: true
  when: required_packages is defined

# - name: "Install apk packages"
#   loop: "{{ required_packages }}"
#   community.general.apk:
#     name: "{{ item }}"
#     update_cache: true
#   when: required_packages is defined
