---
- ansible.builtin.import_playbook: get_localhost_sudo_password.yml
- ansible.builtin.import_playbook: deploy_squid.yml
- ansible.builtin.import_playbook: deploy_pihole.yml
- ansible.builtin.import_playbook: deploy_portainer.yml
