---
- name: Create base CT template
  hosts: base-ct
  gather_facts: false
  tasks:

    - name: Check if base-ct is already a template
      delegate_to: prox
      vars: ### NOTE: Workaround, only required when container isn't online
        ansible_ssh_private_key_file: "{{ hostvars['prox'].ansible_ssh_private_key_file }}"
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          grep template /etc/pve/lxc/{{ id }}.conf
        executable: /bin/bash
      register: check_if_base_ct_exists
      changed_when: check_if_base_ct_exists.rc != 0
      failed_when: false ### Ignore fails, just want stdout


    ### Create --> Start --> Install packages
    # - name: "Include role 'prox_lxc' to create/backup/destroy base container"
    #   loop:
    #     - check_create_install_packages
    #     - vzdump
    #     - destroy
    #   ansible.builtin.include_role:
    #     name: prox_lxc
    #     tasks_from: "{{ item }}"
    #   when: check_if_base_ct_exists.stdout == ""


    - name: If base template does not exist
      when: check_if_base_ct_exists.stdout == ""
      block:

        - name: Include role 'prox_lxc'
          loop:
            - check_create_install_packages
            - vzdump
            - destroy
          ansible.builtin.include_role:
            name: prox_lxc


        # ### Stop
        # - name: Stop container
        #   delegate_to: localhost
        #   community.general.proxmox:
        #     api_host: "{{ hostvars['prox'].ansible_ssh_host }}"
        #     api_user: root@pam
        #     api_password: "{{ lookup('file', password_file) }}"

        #     vmid: "{{ id }}"
        #     state: stopped

        ### VZdump
        # - name: "Backup container with vzdump"
        #   delegate_to: prox
        #   vars: ### NOTE: Workaround for when the container isn't responding
        #     ansible_ssh_private_key_file: "{{ hostvars['prox'].ansible_ssh_private_key_file }}"
        #   ansible.builtin.command: "vzdump {{ id }} --mode stop --dumpdir {{ prox_ct_template_dir }}/ --compress zstd"
        #   register: vzdump_container
        #   changed_when: vzdump_container.rc != 0

        # - name: "DEBUG: Show output of container backup"
        #   ansible.builtin.debug:
        #     var: vzdump_container.stdout_lines

        # - name: "DEBUG: Include role 'prox_lxc' with tasks from 'show_vzdump_backups'"
        #   ansible.builtin.include_role:
        #     name: prox_lxc
        #     tasks_from: show_vzdump_backups


        # ### Template
        # - name: Convert CT to template
        #   vars: ### NOTE: Workaround, only required when container isn't online
        #     ansible_ssh_private_key_file: "{{ hostvars['prox'].ansible_ssh_private_key_file }}"
        #   delegate_to: prox
        #   block:

        #     - name: Stop CT
        #       ansible.builtin.command: "pct stop {{ id }}"
        #       register: convert_base_vm_to_template
        #       changed_when: convert_base_vm_to_template.rc != 0

        #     - name: Remove network config
        #       ansible.builtin.command: "pct set {{ id }} --delete net0"
        #       register: remove_network_config
        #       changed_when: remove_network_config.rc != 0

        #     - name: Convert base CT to template
        #       ansible.builtin.command: "pct template {{ id }}"
        #       register: convert_base_vm_to_template
        #       changed_when: convert_base_vm_to_template.rc != 0
