---
- name: Destroy base CT
  hosts: base-ct
  gather_facts: false
  tasks:

    - name: Destroy base CT
      ansible.builtin.include_role:
        name: prox_lxc
        tasks_from: destroy

    - name: Delete old SSH keys
      ansible.builtin.include_role:
        name: ssh
        tasks_from: remove
