---
- name: Destroy all VMs
  hosts: vms, !base-vm
  gather_facts: false
  tasks:

    - name: Destroy all VMs
      ansible.builtin.include_role:
        name: prox_kvm
        tasks_from: destroy

    - name: Delete old SSH keys
      ansible.builtin.include_role:
        name: ssh
        tasks_from: remove
