### TODO: Use this playbook instead of 'prox_password.txt'

### If the proxmox password is required please import this playbook first.
### This ensure that interactive user input is out of the way ASAP,
### and the playbook can continue without interruption.

---
- name: Get Proxmox password (if not defined)
  hosts: prox
  gather_facts: false
  tasks:

    - name: Get Proxmox password
      when: proxmox_password is not defined
      block:

        - name: Get Proxmox password
          ansible.builtin.pause:
            prompt: Please enter the password to your Proxmox installation
            echo: false
          register: pause_result

        - name: Set 'proxmox_password'
          ansible.builtin.set_fact:
            proxmox_password: "{{ pause_result.user_input }}"
