---
- name: "Create base CT template"
  hosts: base
  gather_facts: false
  tasks:

    - name: "Check if base template exists"
      delegate_to: prox
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          ls {{ template_dir }}/vzdump-lxc-{{ id }}*tar.zst | head -n1
        executable: /bin/bash
      register: check_base_template_result
      changed_when: check_base_template_result.rc != 0
      failed_when: false ### Ignore fails, just want stdout

    - name: "Create base container"
      when: check_base_template_result.stdout == ""
      block:
        - name: "Create base container"
          ansible.builtin.include_role:
            name: create_lxc

        - name: "Backup base container"
          loop:
            - backup_lxc
            - destroy_lxc
          ansible.builtin.include_role:
            name: "{{ item }}"

    # - name: "DEBUG: Show VZdump backup dir contents"
    #   ansible.builtin.include_role:
    #     name: backup_lxc
    #     tasks_from: show_vzdump_backups.yml
