---
- name: "Create base CT template"
  hosts: base
  gather_facts: false
  tasks:

    - name: "Check if base template exists"
      vars: ### NOTE: Workaround, only required when container isn't online
        ansible_ssh_private_key_file: "{{ hostvars['prox'].ansible_ssh_private_key_file }}"
      delegate_to: prox
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          ls {{ prox_ct_template_dir }}/vzdump-lxc-{{ id }}*tar.zst | head -n1
        executable: /bin/bash
      register: check_base_template_result
      changed_when: check_base_template_result.rc != 0
      failed_when: false ### Ignore fails, just want stdout

    - name: "Include role 'prox_lxc' to create/backup/destroy base container"
      loop:
        - check_before_create
        - install_packages
        - backup
        - destroy
      ansible.builtin.include_role:
        name: prox_lxc
        tasks_from: "{{ item }}"
      when: check_base_template_result.stdout == ""

    - name: "DEBUG: Include role 'prox_lxc' with tasks from 'show_vzdump_backups'"
      ansible.builtin.include_role:
        name: prox_lxc
        tasks_from: show_vzdump_backups
