---
- name: "Create base CT template"
  hosts: base
  gather_facts: false
  tasks:
    - name: "Ignore strict host key checking"
      ansible.builtin.set_fact:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    - name: "Create base container"
      loop:
        - create
        # - packages
        - backup
        - destroy
      ansible.builtin.include_role:
        name: "{{ item }}"

    # - name: "DEBUG: Get contents of {{ template_dir }}"
    #   delegate_to: prox
    #   ansible.builtin.command: "ls -lh {{ template_dir }}"
    #   register: ls_template_dir
    #   changed_when: ls_template_dir.rc != 0

    # - name: "DEBUG: Show contents of {{ template_dir }}"
    #   ansible.builtin.debug:
    #     var: ls_template_dir.stdout_lines
