---
- name: Set SSH host(s)
  hosts: prox, portainer
  gather_facts: false
  roles:
    - get_ssh_host


- name: Deploy portainer
  hosts: portainer
  gather_facts: false
  tasks:

    ### Create
    - name: Include role 'prox_lxc'
      ansible.builtin.include_role:
        name: prox_lxc


    ### TODO: Check if Portainer is already installed
    ### Start
    - name: Include role 'portainer'
      ansible.builtin.include_role:
        name: portainer

    ### Configure
    - name: Set password
      ansible.builtin.command: |
        http POST \
          http://{{ ansible_ssh_host }}:{{ port }}/api/users/admin/init \
          Username='admin' \
          Password='{{ lookup('file', portainer_password_file) }}'
      register: set_admin_pw
      changed_when: set_admin_pw.rc != 0
