---
- name: Set SSH host(s)
  hosts: prox, pihole
  gather_facts: false
  vars:
    use_ip_not_dns_name: true
  roles:
    - get_ssh_host

- name: Create Pihole CT
  hosts: pihole
  gather_facts: false
  roles:
    - prox_lxc


- name: Install Pihole
  hosts: pihole
  gather_facts: false
  tasks:

    - name: Install pihole
      loop:
        - check_before_install
        - install
      ansible.builtin.include_role:
        name: pihole
        tasks_from: "{{ item }}"

    - name: Populate DNS records
      vars:
        a_records_file: /etc/pihole/custom.list
        cname_records_file: /etc/dnsmasq.d/05-pihole-custom-cname.conf
      ansible.builtin.include_role:
        name: pihole
        tasks_from: populate_records


### Apply DNS to hosts
- name: Migrate DNS to new Pihole container 
  hosts: localhost, prox
  gather_facts: false
  tasks:

    - name: "Disable enterprise repo list"
      vars:
        domain: "{{ domain }}"
        dns: "{{ dns }}"
      ansible.builtin.template:
        src: templates/resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "644"


- name: Verify DNS connection to Proxmox
  hosts: prox
  gather_facts: false
  tasks:

    - name: Reset SSH host to FQDN
      ansible.builtin.include_role:
        name: get_ssh_host

    - name: Run a command on Proxmox
      ansible.builtin.command: id
      register: id_result

    - name: Show command output
      ansible.builtin.debug:
        var: id_result
