---
- name: Set SSH host(s)
  hosts: prox, portainer
  gather_facts: false
  roles:
    - get_ssh_host


- name: Deploy portainer
  hosts: portainer
  gather_facts: false
  tasks:

    ### Create
    - name: Include role 'prox_lxc'
      ansible.builtin.include_role:
        name: prox_lxc


    ### TODO: Check if Portainer is already installed
    ### Start
    - name: Include role 'portainer'
      ansible.builtin.include_role:
        name: portainer

    ### Configure
    - name: Configure Portainer
      delegate_to: localhost
      vars:
        api_url: "{{ http_protocol }}://{{ ansible_ssh_host }}:{{ port }}/api"
      block:

        - name: "DEBUG: api_url"
          ansible.builtin.debug:
            var: api_url

        - name: Set password
          ansible.builtin.command: |
            http POST {{ api_url }}/users/admin/init \
              Username="admin" \
              Password="{{ lookup('file', portainer_password_file) }}"
          register: set_admin_pw
          changed_when: set_admin_pw.rc != 0

        - name: Get JWT token
          ansible.builtin.shell: |
            set -o pipefail
            http POST {{ api_url }}/auth \
              Username="admin" \
              Password="{{ lookup('file', portainer_password_file) }}" \
            | jq -r ."jwt"
          register: get_jwt_token
          changed_when: get_jwt_token.rc != 0

        ### TODO: Loop through all docker_containers
        ### TODO: Move to a role
        - name: Deploy stacks
          ansible.builtin.command: |
            http POST {{ api_url }}/stacks \
              type=="2" \
              method=="repository" \
              endpointId=="2" \
              "Authorization: Bearer {{ get_jwt_token.stdout }}" \
              Name="price_scraper" \
              RepositoryURL="https://github.com/jason-galea/price_scraper"
          register: deploy_stacks
          changed_when: deploy_stacks.rc != 0
