---
- name: Set SSH host(s)
  hosts: prox, portainer
  gather_facts: false
  roles:
    - get_ssh_host


- name: Deploy portainer
  hosts: portainer
  gather_facts: false
  tasks:

    ### Create
    - name: Include role 'prox_lxc'
      ansible.builtin.include_role:
        name: prox_lxc


    ### TODO: Check if Portainer is already installed


    ### Start
    - name: Include role 'portainer'
      ansible.builtin.include_role:
        name: portainer


# ###################################################################################################

#     ### Configure Portainer
#     - name: Set password???

#     - name: Add new stack via API???
