---
- name: Create Portainer CT
  hosts: portainer
  gather_facts: false
  tasks:

    ### Create
    - name: Include role 'prox_lxc'
      ansible.builtin.include_role:
        name: prox_lxc


    ### TODO: Check if Portainer is already installed

    ### Install
    - name: Create 'portainer_data' volume
      community.docker.docker_volume:
      # containers.podman.podman_volume:
        name: portainer_data
        state: present

    - name: Launch Portainer
      community.docker.docker_container:
      # containers.podman.podman_container:
        detach: true
        ports:
          - 8000:8000
          - 9443:9443
        name: portainer
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        image: docker.io/portainer/portainer-ce:latest
        state: started

    - name: "Show new Portainer URL"
      ansible.builtin.debug:
        msg: "https://{{ ansible_ssh_host }}:{{ port }}/"

    - name: "Verify webserver"
      ansible.builtin.wait_for:
        port: "{{ port }}"
        timeout: 5


# ###################################################################################################

#     ### Configure Portainer
#     - name: ???
