---
- name: Import playbook 'create_base_vm.yml'
  ansible.builtin.import_playbook: create_base_vm.yml


- name: Create Portainer VM
  hosts: portainer
  gather_facts: false
  tasks:

    - name: Include role 'prox_kvm'
      ansible.builtin.include_role:
        name: prox_kvm

    # - name: "Install Portainer"
    #   loop:
    #     - check_before_install
    #     - install
    #   ansible.builtin.include_role:
    #     name: portainer
    #     tasks_from: "{{ item }}"


###################################################################################################


    ### Install Portainer!
    # - name: Check if Portainer is already installed

    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        update_cache: true

    - name: Create docker volume for Portainer
      community.docker.docker_volume:
        name: portainer_data
        state: present

    - name: Launch Portainer via docker
      community.docker.docker_container:
        detach: true
        ports:
          - 8000:8000
          - 9443:9443
        name: portainer
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        image: portainer/portainer-ce:latest
        state: started

    - name: "Show new Portainer URL"
      ansible.builtin.debug:
        msg: "https://{{ ansible_ssh_host }}:{{ port }}/"

    - name: "Verify webserver"
      ansible.builtin.wait_for:
        port: "{{ port }}"
        timeout: 5
