---
- name: Set SSH host(s)
  hosts: prox, squid
  gather_facts: false
  vars:
    use_ip_not_dns_name: true
  roles:
    - get-ssh-host

- name: Create Squid CT
  hosts: squid
  gather_facts: false
  tasks:

    ### Create
    - name: Include role 'prox-lxc'
      ansible.builtin.include_role:
        name: prox-lxc
