---
- name: "Create base CT template"
  ansible.builtin.import_playbook: create_base_ct_template.yml


- name: "Create pihole CT"
  hosts: pihole
  gather_facts: false
  tasks:
    - name: "???"
