---
- name: "Create Portainer VM"
  hosts: portainer
  gather_facts: false
  tasks:
    - name: "Create VM"
      ansible.builtin.include_role:
        name: create_vm

    # - name: "Check if Portainer is already installed"

    # - name: "Install Portainer"
