---
- name: Set SSH host(s)
  hosts: prox, gitlab
  gather_facts: false
  roles:
    - get_ssh_host


- name: Deploy Gitlab
  hosts: gitlab
  gather_facts: false
  tasks:

    ### Create
    - name: Include role 'prox_lxc'
      ansible.builtin.include_role:
        name: prox_lxc


    ### Install
    - name: Add Gitlab repo
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
        executable: /bin/bash
      register: add_gitlab_repo
      changed_when: add_gitlab_repo.rc != 0

    # - name: "DEBUG: Show 'Add Gitlab repo' output"
    #   ansible.builtin.debug:
    #     var: add_gitlab_repo.stdout_lines

    - name: Install Gitlab
      ansible.builtin.apt:
        name: gitlab-ee
        update_cache: true
      environment:
        EXTERNAL_URL: "{{ http_protocol }}://{{ fqdn }}"
      register: install_gitlab

    - name: "DEBUG: Show 'Install Gitlab' output"
      ansible.builtin.debug:
        var: install_gitlab

    - name: Get inital root password
      ansible.builtin.command: cat /etc/gitlab/initial_root_password
      register: initial_root_password
      changed_when: initial_root_password.rc != 0

    - name: Show initial root password
      ansible.builtin.debug:
        var: initial_root_password.stdout_lines

    - name: Include role 'verify_webserver'
      ansible.builtin.include_role:
        name: verify_webserver

    # ### Configure
    # - name: Deactive account registration from web UI
    #   ansible.builtin.command: ???
