---
- name: Destroy all CT VZdump backups
  hosts: prox
  gather_facts: false
  tasks:
    - name: Get list of VZdump files
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          find {{ prox_ct_template_dir }}/ | grep vzdump
        executable: /bin/bash
      register: vzdumps_to_destroy
      changed_when: vzdumps_to_destroy.rc != 0
      failed_when: false

    - name: Destroy all CT VZdump backups
      loop: "{{ vzdumps_to_destroy.stdout_lines }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent

    # - name: "DEBUG: Include role 'prox_lxc' with tasks from 'show_vzdump_backups'"
    #   ansible.builtin.include_role:
    #     name: prox_lxc
    #     tasks_from: show_vzdump_backups
