---
- name: Set SSH host(s)
  hosts: prox, squid
  gather_facts: false
  vars:
    use_ip_not_dns_name: true
  roles:
    - get_ssh_host

- name: Destroy squid container
  hosts: squid
  gather_facts: false
  tasks:

    - name: Destroy squid container
      ansible.builtin.include_role:
        name: prox_lxc
        tasks_from: destroy

    - name: Delete old SSH keys
      ansible.builtin.include_role:
        name: ssh
        tasks_from: remove
