---
- name: Destroy VM template
  hosts: base-vm
  gather_facts: false
  tasks:

    - name: Destroy VM template
      ansible.builtin.include_role:
        name: prox_kvm
        tasks_from: destroy

    - name: Delete old SSH keys
      ansible.builtin.include_role:
        name: ssh
        tasks_from: remove
