### If localhost sudo is required please import this playbook first.

### This ensure that interactive user input is out of the way ASAP,
### and the playbook can continue without interruption.

### If this playbook is imported multiple times from parent & child playbooks,
### user input will only be required for the first import.

---
- name: Get localhost sudo password (if not defined)
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Get localhost sudo password
      when: ansible_become_password is not defined
      block:

        - name: Get localhost sudo password
          ansible.builtin.pause:
            prompt: Please enter your localhost sudo password
            echo: false
          register: pause_result

        - name: Set fact 'ansible_become_password'
          ansible.builtin.set_fact:
            ansible_become_password: "{{ pause_result.user_input }}"
