all:
  hosts:
    prox:
      ansible_user: "{{ inventory_hostname }}" # ie. "prox"
      ansible_host: 172.26.0.2
  children:
    prox_hosts_all_ips:
      hosts:
        # portainer:
        #   id: "160"
        pihole:
          id: "161"
        # apache:
        #   id: "162"
        #   port: "80"
        # emby:
        #   id: "163"
        #   port: "8096" # HTTP
        #   # port: "8920" # HTTPS
        # wekan:
        #   id: "164"
        #   port: "3001"
          # features: ??? # Not worth it here, just use services/wekan.yml
        # radarr:
        #   id: "171"
        #   user: "admin"
      vars: ### Note that any host can choose to override these default values
        unprivileged: 1 # TODO: TEST ALL SERVICES TO CONFIRM!
        network: "172.26.0."
        user: "{{ inventory_hostname }}"
        # This ^^^ seems redundant, but if we use "inventory_hostname" in the playbook instead,
        # we are unable to change usernames on a per host basis.
        # For example, radarr/sonarr/lidarr do NOT want the user to be created in advance,
        # as they do it themselves during installation.
        # In that case we need explicit usernames that DON'T match "inventory_hostname"
        # So, we would override the username here, and the inventory remains the single source of truth.
        ansible_user: "{{ inventory_hostname }}"
        # ^^^ Same as above, I would need to modify every playbook.
        # Unlike above though, this SHOULD be a permanent change.
        # So, I'll deprecate "user" once "ansible_user" has been tested more thoroughly
        # ansible_user: root
        # ^^^ Root is only required for the "configure.yml" playbook.
        # After passwordless sudo is enabled, default user (eg. "wekan")
        # will be able to "become: yes" without a prompt.
        ### Just to be clear, having DNS & FQDNs would allow for this clean solution:
        # user: "{{ split(inventory_hostname, '.')[0] }}"
        # wekan.test.lan --> user = "wekan"
        ansible_host: "{{ network + id }}"
