---
- name: Create Portainer VM
  hosts: portainer
  gather_facts: false
  tasks:

    - name: Stop portainer
      community.docker.docker_container:
        name: portainer
        state: stopped

    ### Easier to get stdout/stderr from a raw command
    - name: Reset password
      ansible.builtin.command:
        docker run --rm -v portainer_data:/data portainer/helper-reset-password
      register: portainer_reset_password
      changed_when: portainer_reset_password.rc != 0


    - name: Show new password
      ansible.builtin.debug:
        var: portainer_reset_password.stderr_lines

    - name: Start Portainer again
      community.docker.docker_container:
        name: portainer
        state: started

    - name: "Show new Portainer URL"
      ansible.builtin.debug:
        msg: "https://{{ ansible_ssh_host }}:{{ port }}/"

    - name: "Verify webserver"
      ansible.builtin.wait_for:
        port: "{{ port }}"
        timeout: 5
