---
- ansible.builtin.import_playbook: get_localhost_sudo_password.yml


- name: Set SSH host(s)
  hosts: prox
  gather_facts: false
  vars:
    use_ip_not_dns_name: true
  roles:
    - get_ssh_host


- name: Revert DNS server to original settings
  hosts: localhost, prox
  gather_facts: false
  tasks:

    - name: Include role 'pihole' with tasks from 'update_resolv_conf'
      vars:
        domain: "{{ backup_domain }}"
        dns: "{{ backup_dns }}"
      ansible.builtin.include_role:
        name: pihole
        tasks_from: update_resolv_conf

    # - name: Add backup domain & dns server to {{ resolv }}
    #   become: true
    #   vars:
    #     domain: "{{ backup_domain }}"
    #     dns: "{{ backup_dns }}"
    #   ansible.builtin.template:
    #     src: templates/resolv.conf.j2
    #     dest: "{{ resolv }}"
    #     owner: root
    #     group: root
    #     mode: "644"

    # - name: Get contents of {{ resolv }}
    #   ansible.builtin.command: cat {{ resolv }}
    #   register: cat_resolv
    #   changed_when: cat_resolv.rc != 0

    # - name: Show contents of {{ resolv }}
    #   ansible.builtin.debug:
    #     var: cat_resolv.stdout_lines
