---
- name: Create Portainer VM
  hosts: portainer
  gather_facts: false
  tasks:

    - name: Stop portainer
      community.docker.docker_container:
        name: portainer
        state: stopped

    ### Easier to get stdout/stderr from a raw command
    - name: Reset password
      ansible.builtin.command:
        docker run --rm -v portainer_data:/data portainer/helper-reset-password
      register: portainer_reset_password
      changed_when: portainer_reset_password.rc != 0


    - name: Show new password
      ansible.builtin.debug:
        var: portainer_reset_password.stderr_lines

    - name: Start Portainer again
      community.docker.docker_container:
        name: portainer
        state: started

    - name: Include role 'verify_webserver'
      ansible.builtin.include_role:
        name: verify_webserver
