- name: "DEBUG: Show ISO"
  ansible.builtin.debug:
    var: chosen_iso


### Create VM
- name: "Create VM"
  delegate_to: localhost
  community.general.proxmox_kvm:
    api_host: "{{ hostvars['prox'].ansible_ssh_host }}"
    api_user: root@pam
    api_password: "{{ hostvars['prox'].password }}"

    name: "{{ inventory_hostname }}"
    vmid: "{{ id }}"

    node: prox
    state: present
    net:
      net0: "virtio,bridge=vm0"
    sockets: 1
    cores: 2
    memory: 512
    scsihw: virtio-scsi-single
    scsi:
      sata0: "local-lvm:32,format=qcow2"
    bios: ovmf
    efidisk0:
      storage: local-lvm
      format: raw
      efitype: 4m
      pre_enrolled_keys: false
    autostart: true


    # # netif: "{{ ct_netif }}"
    # netif: '{"net0":"name=eth0,bridge=vmbr0,firewall=1,type=veth,ip={{ ansible_ssh_host }}/24,gw={{ gateway }}"}'
    # ???: "{{ chosen_iso }}"
    # hostname: "{{ inventory_hostname }}"
    # # password: "{{ hostvars['prox'].password }}"
    # pubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    # cores: 2
    # memory: 512 # MB
    # swap: 100 # MB
    # disk: 8 # GB
    # storage: local-lvm
    # # [DEPRECATION WARNING]: The default value `false` for the parameter "unprivileged" is deprecated and it will be
    # # replaced with `true`. This feature will be removed from community.general in version 7.0.0. Deprecation warnings
    # # can be disabled by setting deprecation_warnings=False in ansible.cfg.
    # unprivileged: true
    # onboot: true
    # features:
    #   - nesting=1


# ### Start
# - name: "Start VM"
#   delegate_to: localhost
#   community.general.proxmox:
#     api_host: "{{ hostvars['prox'].ansible_ssh_host }}"
#     api_user: root@pam
#     api_password: "{{ hostvars['prox'].password }}"

#     vmid: "{{ id }}"
#     state: started

# - name: "Wait 5 seconds to VM to start"
#   ansible.builtin.pause:
#     seconds: 5


### Verify
- name: "Verify VM is online"
  delegate_to: localhost
  ansible.builtin.wait_for_connection:
    timeout: 5
# - name: "Verify VM is online"
#   ansible.builtin.wait_for_connection:
#     port: 22
#     timeout: 5
#   retries: 3

- name: "Add new SSH key to known hosts"
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      ssh-keyscan -H {{ ansible_ssh_host }} >> ~/.ssh/known_hosts
    executable: /bin/bash
  register: add_to_known_hosts
  changed_when: add_to_known_hosts.rc != 0

- name: "DEBUG: Run 'id' command on new VM"
  ansible.builtin.command: "id"
  register: id_command_result
  changed_when: id_command_result != 0

- name: "DEBUG: Show 'id' command output"
  ansible.builtin.debug:
    var: id_command_result.stdout
