---
- name: "Destroy containers"
  hosts: prox_hosts
  gather_facts: no
  vars:
    ansible_user: root
  tasks:
  - delegate_to: localhost
    proxmox:
      api_host: "{{ prox_host }}"
      api_user: "{{ prox_user }}"
      api_password: "{{ prox_password }}"

      vmid: "{{ id }}"
      state: absent